// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlpkqtwvbpntaqdoevnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpscGtxdHd2YnBudGFxZG9ldm5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMDA0ODIsImV4cCI6MjA2NzY3NjQ4Mn0.8jVWnGuLUiEJj866tkLBIiaPb19Ck0G63fQY3cdWKdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});